In [ ]:
!pip install numpy pandas scikit-learn tensorflow matplotlib

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.9.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.76.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.2.5)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.18.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.11.12)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.4)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
np.random.seed(42)

NUM_SAMPLES = 3000
data = []

for _ in range(NUM_SAMPLES):
    session_duration = np.random.randint(1, 90)
    scrolls_per_minute = np.random.randint(5, 80)
    app_switch_rate = round(np.random.uniform(0, 10), 2)
    idle_gap_ratio = round(np.random.uniform(0, 0.5), 2)
    night_usage = np.random.choice([0, 1], p=[0.7, 0.3])
    entertainment_ratio = round(np.random.uniform(0, 1), 2)
    reopen_count = np.random.randint(0, 15)
    session_burst_score = round(np.random.uniform(0, 1), 2)

    doomscrolling = 0
    if (
        session_duration > 25 and
        scrolls_per_minute > 35 and
        entertainment_ratio > 0.6 and
        idle_gap_ratio < 0.1 and
        (night_usage == 1 or session_burst_score > 0.6)
    ):
        doomscrolling = 1

    data.append([
        session_duration,
        scrolls_per_minute,
        app_switch_rate,
        idle_gap_ratio,
        night_usage,
        entertainment_ratio,
        reopen_count,
        session_burst_score,
        doomscrolling
    ])

columns = [
    "session_duration",
    "scrolls_per_minute",
    "app_switch_rate",
    "idle_gap_ratio",
    "night_usage",
    "entertainment_ratio",
    "reopen_count",
    "session_burst_score",
    "doomscrolling"
]

df = pd.DataFrame(data, columns=columns)
df.head()

,session_duration,scrolls_per_minute,app_switch_rate,idle_gap_ratio,night_usage,entertainment_ratio,reopen_count,session_burst_score,doomscrolling
0,52,19,7.32,0.30,0,0.16,10,0.46,0
1,24,7,0.21,0.48,1,0.21,11,0.18,0
2,76,62,5.25,0.22,0,0.61,9,0.05,0
3,60,19,4.56,0.39,0,0.51,8,0.05,0
4,51,11,1.71,0.03,1,0.97,1,0.39,0

In [ ]:
df["doomscrolling"].value_counts()

doomscrolling
0    2948
1      52
Name: count, dtype: int64

In [ ]:
X = df.drop("doomscrolling", axis=1)
y = df["doomscrolling"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
model = Sequential([
    Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 289 (1.13 KB)

 Trainable params: 289 (1.13 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.4421 - loss: 0.7276 - val_accuracy: 0.9000 - val_loss: 0.4710
Epoch 2/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9521 - loss: 0.4074 - val_accuracy: 0.9854 - val_loss: 0.2835
Epoch 3/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9831 - loss: 0.2508 - val_accuracy: 0.9854 - val_loss: 0.1813
Epoch 4/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9876 - loss: 0.1606 - val_accuracy: 0.9854 - val_loss: 0.1275
Epoch 5/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9845 - loss: 0.1202 - val_accuracy: 0.9854 - val_loss: 0.1008
Epoch 6/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9843 - loss: 0.0936 - val_accuracy: 0.9854 - val_loss: 0.0857
Epoch 7/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9870 - loss: 0.0732 - val_accuracy: 0.9854 - val_loss: 0.0765
Epoch 8/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9865 - loss: 0.0648 - val_accuracy: 0.9854 - val_loss: 0.0701
Epoch 9/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9858 - loss: 0.0603 - val_accuracy: 0.9854 - val_loss: 0.0654
Epoch 10/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9829 - loss: 0.0633 - val_accuracy: 0.9854 - val_loss: 0.0612
Epoch 11/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9811 - loss: 0.0604 - val_accuracy: 0.9854 - val_loss: 0.0579
Epoch 12/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9832 - loss: 0.0555 - val_accuracy: 0.9854 - val_loss: 0.0550
Epoch 13/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9864 - loss: 0.0434 - val_accuracy: 0.9854 - val_loss: 0.0525
Epoch 14/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9828 - loss: 0.0464 - val_accuracy: 0.9854 - val_loss: 0.0507
Epoch 15/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9788 - loss: 0.0552 - val_accuracy: 0.9854 - val_loss: 0.0488
Epoch 16/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9887 - loss: 0.0346 - val_accuracy: 0.9854 - val_loss: 0.0477
Epoch 17/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9846 - loss: 0.0404 - val_accuracy: 0.9854 - val_loss: 0.0468
Epoch 18/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9841 - loss: 0.0431 - val_accuracy: 0.9854 - val_loss: 0.0463
Epoch 19/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9880 - loss: 0.0332 - val_accuracy: 0.9854 - val_loss: 0.0461
Epoch 20/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9911 - loss: 0.0315 - val_accuracy: 0.9854 - val_loss: 0.0455

In [ ]:
y_pred = (model.predict(X_test) > 0.75).astype(int)

print(classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       585
           1       0.00      0.00      0.00        15

    accuracy                           0.97       600
   macro avg       0.49      0.50      0.49       600
weighted avg       0.95      0.97      0.96       600

Confusion Matrix:
 [[585   0]
 [ 15   0]]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
model.export("neuropulse_saved_model")

NameError: name 'model' is not defined

In [ ]:
converter = tf.lite.TFLiteConverter.from_saved_model("neuropulse_saved_model")
tflite_model = converter.convert()

with open("neuropulse_model.tflite", "wb") as f:
    f.write(tflite_model)

In [ ]:
from google.colab import files
files.download("neuropulse_model.tflite")

In [ ]:
from google.colab import files
files.upload()

Saving neuropulse_model.tflite to neuropulse_model (1).tflite

{'neuropulse_model (1).tflite': b'\x1c\x00\x00\x00TFL3\x14\x00 \x00\x1c\x00\x18\x00\x14\x00\x10\x00\x0c\x00\x00\x00\x08\x00\x04\x00\x14\x00\x00\x00\x1c\x00\x00\x00\x8c\x00\x00\x00\xe4\x00\x00\x00\x90\x06\x00\x00\xa0\x06\x00\x004\x0c\x00\x00\x03\x00\x00\x00\x01\x00\x00\x00\x04\x00\x00\x00"\xf9\xff\xff\x0c\x00\x00\x00\x1c\x00\x00\x00<\x00\x00\x00\x0f\x00\x00\x00serving_default\x00\x01\x00\x00\x00\x04\x00\x00\x00\x90\xff\xff\xff\n\x00\x00\x00\x04\x00\x00\x00\x08\x00\x00\x00output_0\x00\x00\x00\x00\x01\x00\x00\x00\x04\x00\x00\x00\x12\xfa\xff\xff\x04\x00\x00\x00\x0c\x00\x00\x00keras_tensor\x00\x00\x00\x00\x02\x00\x00\x004\x00\x00\x00\x04\x00\x00\x00\xdc\xff\xff\xff\r\x00\x00\x00\x04\x00\x00\x00\x13\x00\x00\x00CONVERSION_METADATA\x00\x08\x00\x0c\x00\x08\x00\x04\x00\x08\x00\x00\x00\x0c\x00\x00\x00\x04\x00\x00\x00\x13\x00\x00\x00min_runtime_version\x00\x0e\x00\x00\x00\xa8\x05\x00\x00\xa0\x05\x00\x00p\x05\x00\x00X\x03\x00\x00D\x03\x00\x00\x14\x03\x00\x00\xc4\x02\x00\x00\xb4\x00\x00\x00\xac\x00\x00\x00\xa4\x00\x00\x00\x9c\x00\x00\x00\x94\x00\x00\x00t\x00\x00\x00\x04\x00\x00\x00\xc6\xfa\xff\xff\x04\x00\x00\x00`\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x08\x00\x0e\x00\x08\x00\x04\x00\x08\x00\x00\x00\x10\x00\x00\x00$\x00\x00\x00\x00\x00\x06\x00\x08\x00\x04\x00\x06\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x0c\x00\x18\x00\x14\x00\x10\x00\x0c\x00\x04\x00\x0c\x00\x00\x00]\x1d\xc6\x03\x91J$*\x01\x00\x00\x00\x02\x00\x00\x00\x04\x00\x00\x00\x06\x00\x00\x002.19.0\x00\x002\xfb\xff\xff\x04\x00\x00\x00\x10\x00\x00\x001.14.0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa0\xf5\xff\xff\xa4\xf5\xff\xff\xa8\xf5\xff\xff\xac\xf5\xff\xff^\xfb\xff\xff\x04\x00\x00\x00\x00\x02\x00\x00\xed\xbcT\xbf\x961%?\xad\xb6\x8e\xbe\xc8a\xcf=6\r\x10\xbe-\xf4\x00\xbfU`\x82\xbe\xdbH\x90>pw\x14\xbe\x9a\xd2^=\rJ\xd2>\xc3\xa8\x12>c\x1b\xde>\xa9\xf0\x12\xbd\xee\xb3T>\xbb2\x91\xbey\x0f\xda\xbe]_\xf9>\xd5\x0eG\xbd\xc8\x87\xd4>G@\xd4>\xd23\xa9\xbe\x93\xbc\x80>\xb3h\xce\xbc\x1aqi>\xbfV$>\x05%\x19?\xc4\xeb\x9d>q\x84\x97\xbe7\x95\xd1\xbe\x8cf\x7f>\xfa\x14\xe2>\xc3:y>\xd5)\x89<]\xe9\xb2>-\n\xb3>\x15\xf5B?\xfe\xe4\xa8\xbe\xfa;"?\xfav|\xbe\xf4\xd9\xd2>\x8d\xa3\x08\xbfq\xa8\x89\xbe\x03\x9ec?\x0f\x83\xe4\xbeH\xa5\xf1>\x98\xef\xe9>v\xa5%\xbd\xf8y\xad<\x96\xef\xa1\xbe\xab?\xb4\xbeK\xeb\x01=v\xdf\x15=I60>\xe0\x8c9\xbe\xb8\x1b\x93>\x92O\xf9\xbd\x99\xfbD\xbfd6\xdc\xbe\xd25\x86\xbe\x02&4\xbe\xbc\x9e\xcc>\xbd\xdc\xf0\xbeN\xf2\xcf=\x95\xfdS>\xdeZ\xf0\xbd\x84\xcd9\xbe\x06\x94\xa6\xbe\x18\xb6\x80\xbc\xba$\x99>p\x8dg\xbe\xf1_{>:@\xa3>\x10\xbfH=\x1e~\xc9>\xdd\n\x0f\xbe\x109\x86\xbe\x05M6\xbf\xa0\xd5\x1e?\x92\xf1\xbf\xbe\xa5\x106>\x19W\r>6\x9b\xcb=\xd2\t\xf1>;>\x03\xbf\xb3\xcd(?er\x99\xbe\x80\x14#\xbf\xb9B\x90>\xd1C\x0f>t\xc3\xb2\xba\x93i\xf3\xbeM\xbf\x00\xbc\xbbR\x0c?T\x0fx\xbe\x04\x009>\xb6\x12\x0f\xbe;\x90\x8c=-\xa1\x07?\xb8\x8b\xb2>\x90^g\xbe\xc3\x982\xbf@\xc3\x1f\xbf_[\xdb>\xa3p\x12>\xab\xcb7\xbb\xf0B\xa7>fR\x9b><=\xed\xbd\xbf\x160\xbe\xb3\x8d[>\xe7\xd8\x8f\xbd~\x07\x8c>\xf05\x81>\x05\xfa\x04\xbf,\xf2 ?n\xd4\x13?^R\xba\xbe\xba\x90\x8a\xbc\xb5\x7f\xac\xbe[\xe9\xb5\xbeZ\xf8\\\xbf\xb7\xcaj\xbe\xde!\xd5\xbet\'\x00\xbf\x90\x8c\xb3=C\x92\xc2\xbe\x18\xc2_\xbej\xfd\xff\xff\x04\x00\x00\x00@\x00\x00\x00\x16\xdf\x03?2E\xb8\xbd\xe4Dc>ilh>h\xbb\xa1>\xf1\xbb\xbf>"\xbc\x1a\xbeWaz>\\\xbb\xd3\xbdd\xa4\xb8>\x05@\x8c>\xaa,p\xbd\x18\x9d\xdf>J\x82\x18\xbe \xa9\xe6>\xecu\xb9>\xb6\xfd\xff\xff\x04\x00\x00\x00 \x00\x00\x00\xe2\xd7\xa4>\x90e\xe0\xbd\x8c\x12w=o\'\xf9\xbd\x07(\xc1\xbd\xa1\x85N\xbdq\xdb\x86\xbdo\xb5\x91>\xe2\xfd\xff\xff\x04\x00\x00\x00\x04\x00\x00\x00\x91\xd3O\xbe\xf2\xfd\xff\xff\x04\x00\x00\x00\x00\x02\x00\x00\xed\xd9Y?\xb1\xa8\x06?\x8c\x87\r?J\xb6\xa0>K\xc2\xc7=\xae\xcd\xb8>6@T>\xda\x0b\xd5>\x1fs\xa6\xbd\x01\\\x04>\xc6\xcab>v&\x9b=\x9e\x87\x1e?c\x93g>?\xefm?^\'\'?\x1a\xf4\xd9\xbe\xeay\x0f\xbf~b\xa9>..]\xbec\xb0\x84>,v\xb6=\xfdt\x81>\xbb"t\xbe\x9a\xb3\xdd\xbe\x05\xa7\x82\xber\nE>$U\xbb\xbe\xd8\xaa?>\x00k\r\xbf\x8f\x04\xff\xbe\x9a*\x0c>Qb\x83<\xc0\x13\xe2>\xaf\xec\x92\xbe\xed\xac\xd2=\xaef\xb4\xbe\xba\x96\xec>)\xd8\xa0=\x84j\x97\xbeCh\xd6>\x8b\x94 >\x9f\xc4\x01\xbe\x16]\xf7\xbej\xb5\xd8>\xcam\xc7>\xaf\xce\xf3:[R\x1c?3\x8f\xa5\xbd\x80M\x8a=I\xf5Q=\xb0vA\xbe7\x18\x0b\xbf\xf8\xb3\x12\xbe\xbe\xd83\xbe\xb7Ia>iw\xa1\xbe\xb6\xa1f>s\xcd\xe2\xbd\xe3\x0b\x0c\xbeB\x81\xed\xbeT\xb6\x91>J?\x9a>\x83\xc4\x19>\xee\x1b\x0b\xbf\xc4\xfe6<\xef\xeb\n\xbf\xc3h\x9e>J\x97\x8b\xbe\x86\xb0\xeb\xbe\xd5\x05\x1c>\xfb\xad\n\xbf2\x94\x88>t\xc3\xba\xbe\xfc4\x88<\xe3k\xd4=`\xe4w>\xb5a\xc4\xbd\x98U\x87\xbe\x0b\xc9&>W\x88\x99=\xd3\r\x11\xbf\xd2\x15\x94\xbeX\xc3-\xbe\xc0*}>\x98V\n>\x8f\x9d\xa9\xbe\x8f!\xb8>\xe8\xcf\xa4>\xb5\x93\xf3\xbd\xaey!\xbf\xac\xda\xf2>\xeaA\xe6=He\xe9\xbc\xb5;\xb3\xbe!\x91\xc8\xbe\x99\x9cI>\xd3\x7f\t>\xa8f\x9b\xbe\x05\xc5\xda;h\x1b;\xbe\x14o\xda\xbe=W\x81=\x83\xf7\x84\xbe\x8c\x8a\xfa>\xb8\x9e^>&\xac\xe8\xbe\x8bi\x17?\xb9\x0f\x84\xbe~\n\x1e>[\x87J>\xff\x10Z\xbe\x18#\xce>T\xb4\x84\xbd\xc1\xb7\xb8=\x15\xd5H>S\xdd\xb1>e/\xf2>md\x1d\xbe\x19\xd6\x0c?\xd7Q\xc4\xbe\xf3o5?\xe0\xd5G?\xe6\xa6\x97\xbe\xb5O\x11??\xd47\xbe;IH?\x7f\t\xf3>\x00\x00\x06\x00\x08\x00\x04\x00\x06\x00\x00\x00\x04\x00\x00\x00 \x00\x00\x00\x1e\xd4\xfd\xbe\x82rc>\xfe\x11\x05\xbeV\xc2n>\x9c\xc9\xfd>\xf4\xba\xd8>H\xec ?\xab,\x91\xbf\x84\xfa\xff\xff\x88\xfa\xff\xff\x0f\x00\x00\x00MLIR Converted.\x00\x01\x00\x00\x00\x14\x00\x00\x00\x00\x00\x0e\x00\x18\x00\x14\x00\x10\x00\x0c\x00\x08\x00\x04\x00\x0e\x00\x00\x00\x14\x00\x00\x00\x1c\x00\x00\x00\x08\x01\x00\x00\x0c\x01\x00\x00\x10\x01\x00\x00\x04\x00\x00\x00main\x00\x00\x00\x00\x04\x00\x00\x00\xb0\x00\x00\x00h\x00\x00\x004\x00\x00\x00\x10\x00\x00\x00\x00\x00\n\x00\x10\x00\x0c\x00\x08\x00\x04\x00\n\x00\x00\x00\x0c\x00\x00\x00\x10\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\n\x00\x00\x00\x01\x00\x00\x00\t\x00\x00\x00\x9a\xff\xff\xff\x10\x00\x00\x00\x00\x00\x00\x08\x0c\x00\x00\x00\x10\x00\x00\x000\xfb\xff\xff\x01\x00\x00\x00\t\x00\x00\x00\x03\x00\x00\x00\x08\x00\x00\x00\x01\x00\x00\x00\x03\x00\x00\x00\xca\xff\xff\xff\x10\x00\x00\x00\x00\x00\x00\x08\x10\x00\x00\x00\x14\x00\x00\x00\xba\xff\xff\xff\x00\x00\x00\x01\x01\x00\x00\x00\x08\x00\x00\x00\x03\x00\x00\x00\x07\x00\x00\x00\x02\x00\x00\x00\x04\x00\x00\x00\x00\x00\x0e\x00\x16\x00\x00\x00\x10\x00\x0c\x00\x0b\x00\x04\x00\x0e\x00\x00\x00\x18\x00\x00\x00\x00\x00\x00\x08\x18\x00\x00\x00\x1c\x00\x00\x00\x00\x00\x06\x00\x08\x00\x07\x00\x06\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x07\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x05\x00\x00\x00\x01\x00\x00\x00\n\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\xf8\x03\x00\x00\xa0\x03\x00\x00H\x03\x00\x00\x0c\x03\x00\x00\xb0\x02\x00\x00X\x02\x00\x00\x0c\x02\x00\x00x\x01\x00\x00\xdc\x00\x00\x00`\x00\x00\x00\x04\x00\x00\x00J\xfc\xff\xff\x00\x00\x00\x01\x14\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x0b\x00\x00\x004\x00\x00\x00\x02\x00\x00\x00\xff\xff\xff\xff\x01\x00\x00\x004\xfc\xff\xff\x1b\x00\x00\x00StatefulPartitionedCall_1:0\x00\x02\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\xa2\xfc\xff\xff\x00\x00\x00\x01\x14\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\n\x00\x00\x00T\x00\x00\x00\x02\x00\x00\x00\xff\xff\xff\xff\x01\x00\x00\x00\x8c\xfc\xff\xff8\x00\x00\x00sequential_1/dense_2_1/MatMul;sequential_1/dense_2_1/Add\x00\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x1a\xfd\xff\xff\x00\x00\x00\x01\x14\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\t\x00\x00\x00t\x00\x00\x00\x02\x00\x00\x00\xff\xff\xff\xff\x08\x00\x00\x00\x04\xfd\xff\xffX\x00\x00\x00sequential_1/dense_1_2/MatMul;sequential_1/dense_1_2/Relu;sequential_1/dense_1_2/BiasAdd\x00\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x08\x00\x00\x00\xb2\xfd\xff\xff\x00\x00\x00\x01\x14\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x08\x00\x00\x00l\x00\x00\x00\x02\x00\x00\x00\xff\xff\xff\xff\x10\x00\x00\x00\x9c\xfd\xff\xffR\x00\x00\x00sequential_1/dense_1/MatMul;sequential_1/dense_1/Relu;sequential_1/dense_1/BiasAdd\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x10\x00\x00\x00\x96\xfe\xff\xff\x00\x00\x00\x01\x10\x00\x00\x00\x10\x00\x00\x00\x07\x00\x00\x00(\x00\x00\x00\x1c\xfe\xff\xff\x1b\x00\x00\x00sequential_1/dense_1/MatMul\x00\x02\x00\x00\x00\x10\x00\x00\x00\x08\x00\x00\x00\xde\xfe\xff\xff\x00\x00\x00\x01\x10\x00\x00\x00\x10\x00\x00\x00\x06\x00\x00\x008\x00\x00\x00d\xfe\xff\xff+\x00\x00\x00sequential_1/dense_1/BiasAdd/ReadVariableOp\x00\x01\x00\x00\x00\x10\x00\x00\x002\xff\xff\xff\x00\x00\x00\x01\x10\x00\x00\x00\x10\x00\x00\x00\x05\x00\x00\x00<\x00\x00\x00\xb8\xfe\xff\xff-\x00\x00\x00sequential_1/dense_1_2/BiasAdd/ReadVariableOp\x00\x00\x00\x01\x00\x00\x00\x08\x00\x00\x00\x8a\xff\xff\xff\x00\x00\x00\x01\x10\x00\x00\x00\x10\x00\x00\x00\x04\x00\x00\x00\x1c\x00\x00\x00\x10\xff\xff\xff\x0f\x00\x00\x00arith.constant2\x00\x01\x00\x00\x00\x01\x00\x00\x00\xc2\xff\xff\xff\x00\x00\x00\x01\x10\x00\x00\x00\x10\x00\x00\x00\x03\x00\x00\x00\x1c\x00\x00\x00H\xff\xff\xff\x0f\x00\x00\x00arith.constant1\x00\x02\x00\x00\x00\x08\x00\x00\x00\x10\x00\x00\x00\x00\x00\x16\x00\x18\x00\x14\x00\x00\x00\x10\x00\x0c\x00\x08\x00\x00\x00\x00\x00\x00\x00\x07\x00\x16\x00\x00\x00\x00\x00\x00\x01\x10\x00\x00\x00\x10\x00\x00\x00\x02\x00\x00\x00\x1c\x00\x00\x00\x9c\xff\xff\xff\x0e\x00\x00\x00arith.constant\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x08\x00\x00\x00\x00\x00\x16\x00\x1c\x00\x18\x00\x00\x00\x14\x00\x10\x00\x0c\x00\x00\x00\x00\x00\x08\x00\x07\x00\x16\x00\x00\x00\x00\x00\x00\x01\x14\x00\x00\x00 \x00\x00\x00 \x00\x00\x00\x01\x00\x00\x00<\x00\x00\x00\x02\x00\x00\x00\xff\xff\xff\xff\x08\x00\x00\x00\x04\x00\x04\x00\x04\x00\x00\x00\x1e\x00\x00\x00serving_default_keras_tensor:0\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x08\x00\x00\x00\x02\x00\x00\x00 \x00\x00\x00\x04\x00\x00\x00\xf4\xff\xff\xff\x0e\x00\x00\x00\x00\x00\x00\x0e\x0c\x00\x0c\x00\x0b\x00\x00\x00\x00\x00\x04\x00\x0c\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\t'}

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
interpreter = tf.lite.Interpreter(model_path="neuropulse_model.tflite")
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print("Input details:", input_details)
print("Output details:", output_details)

Input details: [{'name': 'serving_default_keras_tensor:0', 'index': 0, 'shape': array([1, 8], dtype=int32), 'shape_signature': array([-1,  8], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
Output details: [{'name': 'StatefulPartitionedCall_1:0', 'index': 10, 'shape': array([1, 1], dtype=int32), 'shape_signature': array([-1,  1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]

/usr/local/lib/python3.12/dist-packages/tensorflow/lite/python/interpreter.py:457: UserWarning:     Warning: tf.lite.Interpreter is deprecated and is scheduled for deletion in
    TF 2.20. Please use the LiteRT interpreter from the ai_edge_litert package.
    See the [migration guide](https://ai.google.dev/edge/litert/migration)
    for details.

  warnings.warn(_INTERPRETER_DELETION_WARNING)

In [ ]:
def tflite_predict(
    session_duration,
    scrolls_per_minute,
    app_switch_rate,
    idle_gap_ratio,
    night_usage,
    entertainment_ratio,
    reopen_count,
    session_burst_score
):
    # Arrange input EXACTLY as training order
    input_data = np.array([[
        session_duration,
        scrolls_per_minute,
        app_switch_rate,
        idle_gap_ratio,
        night_usage,
        entertainment_ratio,
        reopen_count,
        session_burst_score
    ]], dtype=np.float32)

    # ⚠️ VERY IMPORTANT
    # Apply SAME scaling used during training
    input_data = scaler.transform(input_data).astype(np.float32)

    # Set input tensor
    interpreter.set_tensor(input_details[0]['index'], input_data)

    # Run inference
    interpreter.invoke()

    # Get output
    probability = interpreter.get_tensor(output_details[0]['index'])[0][0]

    # Decision threshold
    if probability > 0.75:
        result = "DOOMSCROLLING RISK 🚨"
    elif probability > 0.5:
        result = "MODERATE RISK ⚠️"
    else:
        result = "NORMAL USAGE ✅"

    return probability, result

In [ ]:
prob, result = tflite_predict(
    session_duration=45,
    scrolls_per_minute=60,
    app_switch_rate=5.0,
    idle_gap_ratio=0.05,
    night_usage=1,
    entertainment_ratio=0.85,
    reopen_count=7,
    session_burst_score=0.9
)

print(f"Probability: {prob:.3f}")
print(f"Prediction: {result}")

Probability: 0.636
Prediction: MODERATE RISK ⚠️

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [ ]:
prob, result = tflite_predict(
    session_duration=8,
    scrolls_per_minute=12,
    app_switch_rate=1.1,
    idle_gap_ratio=0.35,
    night_usage=0,
    entertainment_ratio=0.2,
    reopen_count=1,
    session_burst_score=0.1
)

print(f"Probability: {prob:.3f}")
print(f"Prediction: {result}")

Probability: 0.000
Prediction: NORMAL USAGE ✅

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(42)
N = 3000

data = []

for _ in range(N):
    session_duration = np.random.uniform(1, 90)        # minutes
    scrolls_per_min = np.random.uniform(5, 80)
    app_switch_rate = np.random.uniform(0, 10)
    idle_gap_ratio = np.random.uniform(0, 0.5)
    night_usage = np.random.choice([0, 1], p=[0.7, 0.3])
    entertainment_ratio = np.random.uniform(0, 1)
    reopen_count = np.random.randint(0, 15)
    session_burst = np.random.choice([0, 1], p=[0.7, 0.3])

    # Proxy labeling logic (ground truth approximation)
    doomscrolling = 1 if (
        session_duration > 30 and
        scrolls_per_min > 40 and
        entertainment_ratio > 0.6 and
        idle_gap_ratio < 0.15 and
        (night_usage == 1 or session_burst == 1)
    ) else 0

    data.append([
        session_duration,
        scrolls_per_min,
        app_switch_rate,
        idle_gap_ratio,
        night_usage,
        entertainment_ratio,
        reopen_count,
        session_burst,
        doomscrolling
    ])

columns = [
    "session_duration_minutes",
    "scrolls_per_minute",
    "app_switch_rate",
    "idle_gap_ratio",
    "night_usage",
    "entertainment_ratio",
    "reopen_count",
    "session_burst_score",
    "doomscrolling"
]

df = pd.DataFrame(data, columns=columns)
df.head()

,session_duration_minutes,scrolls_per_minute,app_switch_rate,idle_gap_ratio,night_usage,entertainment_ratio,reopen_count,session_burst_score,doomscrolling
0,34.334071,76.303573,7.319939,0.299329,0,0.155995,10,0,0
1,30.700066,15.715011,6.508885,0.028206,1,0.938553,1,0,0
2,17.323001,27.818168,5.247564,0.215973,0,0.611853,9,0,0
3,87.664241,22.457851,0.906064,0.309193,0,0.983231,8,0,0
4,55.071492,17.789309,0.650516,0.474443,1,0.808397,8,0,0

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop("doomscrolling", axis=1).values
y = df["doomscrolling"].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(16, activation="relu", input_shape=(8,)),
    Dense(8, activation="relu"),
    Dense(1, activation="sigmoid")
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 16)             │           144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 289 (1.13 KB)

 Trainable params: 289 (1.13 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9743 - loss: 0.1400 - val_accuracy: 0.9792 - val_loss: 0.0928
Epoch 2/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9752 - loss: 0.0992 - val_accuracy: 0.9792 - val_loss: 0.0881
Epoch 3/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9768 - loss: 0.0908 - val_accuracy: 0.9792 - val_loss: 0.0850
Epoch 4/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9722 - loss: 0.0990 - val_accuracy: 0.9792 - val_loss: 0.0823
Epoch 5/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9763 - loss: 0.0866 - val_accuracy: 0.9792 - val_loss: 0.0798
Epoch 6/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9743 - loss: 0.0901 - val_accuracy: 0.9792 - val_loss: 0.0775
Epoch 7/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9695 - loss: 0.0990 - val_accuracy: 0.9792 - val_loss: 0.0755
Epoch 8/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9745 - loss: 0.0839 - val_accuracy: 0.9792 - val_loss: 0.0731
Epoch 9/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9707 - loss: 0.0925 - val_accuracy: 0.9792 - val_loss: 0.0713
Epoch 10/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9752 - loss: 0.0753 - val_accuracy: 0.9792 - val_loss: 0.0695
Epoch 11/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9712 - loss: 0.0828 - val_accuracy: 0.9792 - val_loss: 0.0677
Epoch 12/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9819 - loss: 0.0566 - val_accuracy: 0.9792 - val_loss: 0.0662
Epoch 13/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9683 - loss: 0.0812 - val_accuracy: 0.9792 - val_loss: 0.0652
Epoch 14/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9801 - loss: 0.0591 - val_accuracy: 0.9792 - val_loss: 0.0632
Epoch 15/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9719 - loss: 0.0738 - val_accuracy: 0.9792 - val_loss: 0.0617
Epoch 16/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9726 - loss: 0.0678 - val_accuracy: 0.9792 - val_loss: 0.0605
Epoch 17/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9694 - loss: 0.0743 - val_accuracy: 0.9792 - val_loss: 0.0594
Epoch 18/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9740 - loss: 0.0611 - val_accuracy: 0.9792 - val_loss: 0.0584
Epoch 19/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9677 - loss: 0.0691 - val_accuracy: 0.9792 - val_loss: 0.0578
Epoch 20/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9756 - loss: 0.0562 - val_accuracy: 0.9792 - val_loss: 0.0567

In [ ]:
from sklearn.metrics import classification_report

y_pred = (model.predict(X_test) > 0.75).astype(int)
print(classification_report(y_test, y_pred))

19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       588
           1       0.00      0.00      0.00        12

    accuracy                           0.98       600
   macro avg       0.49      0.50      0.49       600
weighted avg       0.96      0.98      0.97       600

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
def manual_test(
    session_duration_minutes,
    scrolls_per_minute,
    app_switch_rate,
    idle_gap_ratio,
    night_usage,
    entertainment_ratio,
    reopen_count,
    session_burst_score
):
    x = np.array([[
        session_duration_minutes,
        scrolls_per_minute,
        app_switch_rate,
        idle_gap_ratio,
        night_usage,
        entertainment_ratio,
        reopen_count,
        session_burst_score
    ]], dtype=np.float32)

    prob = model.predict(x)[0][0]

    if prob > 0.75:
        label = "DOOMSCROLLING RISK 🚨"
    elif prob > 0.5:
        label = "MODERATE RISK ⚠️"
    else:
        label = "NORMAL USAGE ✅"

    return prob, label

In [ ]:
manual_test(
    45, 60, 4.5, 0.05, 1, 0.85, 7, 1
)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step

(np.float32(0.11726334), 'NORMAL USAGE ✅')

In [ ]:
manual_test(
    900, 120, 4.5, 0.5, 1, 0.85, 7, 5
)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

(np.float32(1.494281e-31), 'NORMAL USAGE ✅')

In [ ]:
# Check raw probability distribution
probs = model.predict(X_test).flatten()

print("Min:", probs.min())
print("Max:", probs.max())
print("Mean:", probs.mean())

19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Min: 1.3006459e-08
Max: 0.31215817
Mean: 0.036799334

In [ ]:
def normalize(X):
    mins = np.array([1, 5, 0, 0, 0, 0, 0, 0])
    maxs = np.array([90, 80, 10, 0.5, 1, 1, 15, 1])
    return (X - mins) / (maxs - mins)

X_train = normalize(X_train)
X_test = normalize(X_test)

In [ ]:
history = model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9731 - loss: 0.2184 - val_accuracy: 0.9792 - val_loss: 0.0933
Epoch 2/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9768 - loss: 0.0937 - val_accuracy: 0.9750 - val_loss: 0.0685
Epoch 3/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9701 - loss: 0.0971 - val_accuracy: 0.9708 - val_loss: 0.0646
Epoch 4/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9749 - loss: 0.0688 - val_accuracy: 0.9708 - val_loss: 0.0631
Epoch 5/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9798 - loss: 0.0635 - val_accuracy: 0.9729 - val_loss: 0.0612
Epoch 6/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9776 - loss: 0.0669 - val_accuracy: 0.9750 - val_loss: 0.0590
Epoch 7/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9769 - loss: 0.0651 - val_accuracy: 0.9750 - val_loss: 0.0578
Epoch 8/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9742 - loss: 0.0660 - val_accuracy: 0.9771 - val_loss: 0.0567
Epoch 9/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9737 - loss: 0.0608 - val_accuracy: 0.9771 - val_loss: 0.0561
Epoch 10/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9772 - loss: 0.0552 - val_accuracy: 0.9771 - val_loss: 0.0553
Epoch 11/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9790 - loss: 0.0514 - val_accuracy: 0.9771 - val_loss: 0.0549
Epoch 12/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9797 - loss: 0.0568 - val_accuracy: 0.9771 - val_loss: 0.0543
Epoch 13/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9747 - loss: 0.0542 - val_accuracy: 0.9771 - val_loss: 0.0540
Epoch 14/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9791 - loss: 0.0521 - val_accuracy: 0.9771 - val_loss: 0.0535
Epoch 15/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9818 - loss: 0.0510 - val_accuracy: 0.9771 - val_loss: 0.0534
Epoch 16/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9736 - loss: 0.0622 - val_accuracy: 0.9771 - val_loss: 0.0526
Epoch 17/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9784 - loss: 0.0521 - val_accuracy: 0.9771 - val_loss: 0.0527
Epoch 18/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9779 - loss: 0.0552 - val_accuracy: 0.9771 - val_loss: 0.0524
Epoch 19/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9779 - loss: 0.0556 - val_accuracy: 0.9771 - val_loss: 0.0522
Epoch 20/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9820 - loss: 0.0491 - val_accuracy: 0.9771 - val_loss: 0.0517

In [ ]:
manual_test(
    60, 70, 6, 0.05, 1, 0.9, 10, 1
)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

(np.float32(0.96077496), 'DOOMSCROLLING RISK 🚨')

In [ ]:
manual_test(
    45, 60, 6, 0.05, 1, 0.9, 10, 1
)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

(np.float32(0.8622951), 'DOOMSCROLLING RISK 🚨')

In [ ]:
import pandas as pd

data = []

# ---------------- NORMAL USAGE ----------------
for duration in range(5, 21, 2):                 # 5–20
    for scrolls in range(8, 21, 3):               # 8–20
        for idle in [0.4, 0.45, 0.5]:
            data.append([
                duration,
                scrolls,
                1.0,        # app_switch_rate
                idle,
                0,          # night_usage
                0.15,       # entertainment_ratio
                1,          # reopen_count
                0,          # session_burst_score
                0           # label
            ])

# ---------------- AT-RISK USAGE ----------------
for duration in range(20, 41, 3):                 # 20–40
    for scrolls in range(20, 41, 4):               # 20–40
        for idle in [0.2, 0.25, 0.3]:
            data.append([
                duration,
                scrolls,
                3.0,
                idle,
                0,
                0.45,
                4,
                1,
                1
            ])

# ---------------- DOOMSCROLLING (DAY) ----------------
for duration in range(40, 71, 4):                 # 40–70
    for scrolls in range(45, 71, 5):               # 45–70
        for idle in [0.05, 0.08]:
            data.append([
                duration,
                scrolls,
                5.0,
                idle,
                0,
                0.75,
                8,
                1,
                1
            ])

# ---------------- DOOMSCROLLING (NIGHT) ----------------
for duration in range(50, 91, 5):                 # 50–90
    for scrolls in range(55, 81, 5):               # 55–80
        for idle in [0.03, 0.06]:
            data.append([
                duration,
                scrolls,
                6.5,
                idle,
                1,
                0.9,
                12,
                1,
                1
            ])

df = pd.DataFrame(data, columns=[
    "session_duration_minutes",
    "scrolls_per_minute",
    "app_switch_rate",
    "idle_gap_ratio",
    "night_usage",
    "entertainment_ratio",
    "reopen_count",
    "session_burst_score",
    "doomscrolling"
])

print("Dataset shape:", df.shape)
print(df["doomscrolling"].value_counts())
df.head()

Dataset shape: (450, 9)
doomscrolling
1    330
0    120
Name: count, dtype: int64

,session_duration_minutes,scrolls_per_minute,app_switch_rate,idle_gap_ratio,night_usage,entertainment_ratio,reopen_count,session_burst_score,doomscrolling
0,5,8,1.0,0.40,0,0.15,1,0,0
1,5,8,1.0,0.45,0,0.15,1,0,0
2,5,8,1.0,0.50,0,0.15,1,0,0
3,5,11,1.0,0.40,0,0.15,1,0,0
4,5,11,1.0,0.45,0,0.15,1,0,0

In [ ]:
history = model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9768 - loss: 0.0557 - val_accuracy: 0.9771 - val_loss: 0.0513
Epoch 2/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9730 - loss: 0.0640 - val_accuracy: 0.9771 - val_loss: 0.0510
Epoch 3/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9749 - loss: 0.0595 - val_accuracy: 0.9792 - val_loss: 0.0510
Epoch 4/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9749 - loss: 0.0586 - val_accuracy: 0.9792 - val_loss: 0.0508
Epoch 5/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9760 - loss: 0.0496 - val_accuracy: 0.9792 - val_loss: 0.0511
Epoch 6/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9791 - loss: 0.0498 - val_accuracy: 0.9792 - val_loss: 0.0510
Epoch 7/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.9788 - loss: 0.0487 - val_accuracy: 0.9792 - val_loss: 0.0510
Epoch 8/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 0.9813 - loss: 0.0514 - val_accuracy: 0.9792 - val_loss: 0.0511
Epoch 9/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9789 - loss: 0.0511 - val_accuracy: 0.9792 - val_loss: 0.0507
Epoch 10/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9767 - loss: 0.0527 - val_accuracy: 0.9792 - val_loss: 0.0500
Epoch 11/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9797 - loss: 0.0479 - val_accuracy: 0.9792 - val_loss: 0.0504
Epoch 12/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9728 - loss: 0.0637 - val_accuracy: 0.9792 - val_loss: 0.0495
Epoch 13/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9788 - loss: 0.0455 - val_accuracy: 0.9771 - val_loss: 0.0502
Epoch 14/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9817 - loss: 0.0480 - val_accuracy: 0.9771 - val_loss: 0.0504
Epoch 15/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9733 - loss: 0.0552 - val_accuracy: 0.9792 - val_loss: 0.0495
Epoch 16/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9819 - loss: 0.0476 - val_accuracy: 0.9792 - val_loss: 0.0502
Epoch 17/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9717 - loss: 0.0569 - val_accuracy: 0.9792 - val_loss: 0.0496
Epoch 18/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9742 - loss: 0.0591 - val_accuracy: 0.9792 - val_loss: 0.0492
Epoch 19/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9734 - loss: 0.0550 - val_accuracy: 0.9792 - val_loss: 0.0490
Epoch 20/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9750 - loss: 0.0529 - val_accuracy: 0.9792 - val_loss: 0.0494

In [ ]:
import pandas as pd

data = []

# ---------------- NORMAL USAGE (CLEARLY NORMAL) ----------------
for duration in range(5, 25, 3):
    for scrolls in range(5, 25, 4):
        data.append([
            duration,        # session_duration_minutes
            scrolls,         # scrolls_per_minute
            1.0,             # app_switch_rate
            0.45,            # idle_gap_ratio
            0,               # night_usage
            0.25,            # entertainment_ratio
            1,               # reopen_count
            0,               # session_burst_score
            0                # label
        ])

# ---------------- BORDERLINE (STILL NORMAL) ----------------
# IMPORTANT: These stay label = 0 to avoid false positives
for duration in range(25, 40, 4):
    for scrolls in range(25, 40, 5):
        data.append([
            duration,
            scrolls,
            2.5,
            0.30,
            0,
            0.45,
            3,
            0,
            0
        ])

# ---------------- AT-RISK BUT NOT DOOMSCROLLING ----------------
# Night usage OR entertainment high, but not both
for duration in range(30, 45, 5):
    for scrolls in range(30, 45, 6):
        data.append([
            duration,
            scrolls,
            3.0,
            0.25,
            1,          # night usage
            0.45,       # moderate entertainment
            4,
            0,
            0
        ])

# ---------------- DOOMSCROLLING (STRICT CONDITIONS) ----------------
for duration in range(45, 90, 5):
    for scrolls in range(45, 80, 5):
        data.append([
            duration,
            scrolls,
            5.5,
            0.08,
            1,          # night usage
            0.85,       # high entertainment
            8,
            1,
            1
        ])

df = pd.DataFrame(data, columns=[
    "session_duration_minutes",
    "scrolls_per_minute",
    "app_switch_rate",
    "idle_gap_ratio",
    "night_usage",
    "entertainment_ratio",
    "reopen_count",
    "session_burst_score",
    "doomscrolling"
])

print("Dataset shape:", df.shape)
print(df["doomscrolling"].value_counts())

Dataset shape: (119, 9)
doomscrolling
1    63
0    56
Name: count, dtype: int64

In [ ]:
history = model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.9788 - loss: 0.0476 - val_accuracy: 0.9771 - val_loss: 0.0494
Epoch 2/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.9776 - loss: 0.0485 - val_accuracy: 0.9771 - val_loss: 0.0494
Epoch 3/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.9788 - loss: 0.0508 - val_accuracy: 0.9750 - val_loss: 0.0496
Epoch 4/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.9793 - loss: 0.0473 - val_accuracy: 0.9750 - val_loss: 0.0496
Epoch 5/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9853 - loss: 0.0374 - val_accuracy: 0.9750 - val_loss: 0.0498
Epoch 6/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9711 - loss: 0.0581 - val_accuracy: 0.9750 - val_loss: 0.0491
Epoch 7/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9805 - loss: 0.0447 - val_accuracy: 0.9750 - val_loss: 0.0490
Epoch 8/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9790 - loss: 0.0523 - val_accuracy: 0.9750 - val_loss: 0.0493
Epoch 9/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9754 - loss: 0.0542 - val_accuracy: 0.9750 - val_loss: 0.0487
Epoch 10/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9790 - loss: 0.0446 - val_accuracy: 0.9750 - val_loss: 0.0494
Epoch 11/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9788 - loss: 0.0490 - val_accuracy: 0.9750 - val_loss: 0.0489
Epoch 12/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9760 - loss: 0.0463 - val_accuracy: 0.9750 - val_loss: 0.0485
Epoch 13/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9808 - loss: 0.0502 - val_accuracy: 0.9750 - val_loss: 0.0488
Epoch 14/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.9752 - loss: 0.0502 - val_accuracy: 0.9771 - val_loss: 0.0484
Epoch 15/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9803 - loss: 0.0497 - val_accuracy: 0.9750 - val_loss: 0.0487
Epoch 16/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9755 - loss: 0.0479 - val_accuracy: 0.9750 - val_loss: 0.0484
Epoch 17/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9797 - loss: 0.0438 - val_accuracy: 0.9750 - val_loss: 0.0488
Epoch 18/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9740 - loss: 0.0608 - val_accuracy: 0.9750 - val_loss: 0.0481
Epoch 19/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9799 - loss: 0.0486 - val_accuracy: 0.9750 - val_loss: 0.0487
Epoch 20/20
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9748 - loss: 0.0546 - val_accuracy: 0.9750 - val_loss: 0.0481

In [ ]:
manual_test(35, 30, 2.5, 0.3, 0, 0.45, 3, 0)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

(np.float32(0.26797128), 'NORMAL USAGE ✅')

In [ ]:
manual_test(70, 65, 6, 0.05, 1, 0.9, 10, 1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

(np.float32(0.9931265), 'DOOMSCROLLING RISK 🚨')

In [ ]:
manual_test(70, 65, 6, 0.05, 1, 0.9, 10, 1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step

(np.float32(0.9931265), 'DOOMSCROLLING RISK 🚨')

In [ ]:
probs = model.predict(X_test).flatten()

print("Min:", probs.min())
print("Max:", probs.max())
print("Mean:", probs.mean())

19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
Min: 2.975043e-14
Max: 0.56289315
Mean: 0.025854276

In [ ]:
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

class_weight_dict = {
    0: class_weights[0],
    1: class_weights[1]
}

print(class_weight_dict)

{0: np.float64(0.5121638924455826), 1: np.float64(21.05263157894737)}

In [ ]:
history = model.fit(
    X_train,
    y_train,
    epochs=30,
    batch_size=16,
    validation_split=0.2,
    class_weight=class_weight_dict,
    verbose=1
)

Epoch 1/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9370 - loss: 0.3865 - val_accuracy: 0.9125 - val_loss: 0.1742
Epoch 2/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9036 - loss: 0.1809 - val_accuracy: 0.9250 - val_loss: 0.1656
Epoch 3/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9052 - loss: 0.1778 - val_accuracy: 0.9125 - val_loss: 0.2075
Epoch 4/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9072 - loss: 0.1847 - val_accuracy: 0.9187 - val_loss: 0.1897
Epoch 5/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9114 - loss: 0.1805 - val_accuracy: 0.9292 - val_loss: 0.1496
Epoch 6/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9386 - loss: 0.1409 - val_accuracy: 0.9187 - val_loss: 0.1979
Epoch 7/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9241 - loss: 0.1457 - val_accuracy: 0.9229 - val_loss: 0.1880
Epoch 8/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9234 - loss: 0.1387 - val_accuracy: 0.9229 - val_loss: 0.1923
Epoch 9/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.9109 - loss: 0.1448 - val_accuracy: 0.9208 - val_loss: 0.2018
Epoch 10/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9147 - loss: 0.1552 - val_accuracy: 0.9229 - val_loss: 0.1980
Epoch 11/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9240 - loss: 0.1361 - val_accuracy: 0.9292 - val_loss: 0.1830
Epoch 12/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9234 - loss: 0.1379 - val_accuracy: 0.9271 - val_loss: 0.1887
Epoch 13/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9273 - loss: 0.1296 - val_accuracy: 0.9271 - val_loss: 0.1909
Epoch 14/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9184 - loss: 0.1455 - val_accuracy: 0.9292 - val_loss: 0.1820
Epoch 15/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9324 - loss: 0.1420 - val_accuracy: 0.9250 - val_loss: 0.1957
Epoch 16/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9269 - loss: 0.1344 - val_accuracy: 0.9271 - val_loss: 0.1893
Epoch 17/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9373 - loss: 0.1098 - val_accuracy: 0.9271 - val_loss: 0.1890
Epoch 18/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9118 - loss: 0.1344 - val_accuracy: 0.9250 - val_loss: 0.2070
Epoch 19/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9072 - loss: 0.1445 - val_accuracy: 0.9312 - val_loss: 0.1850
Epoch 20/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9225 - loss: 0.1328 - val_accuracy: 0.9312 - val_loss: 0.1881
Epoch 21/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9313 - loss: 0.1342 - val_accuracy: 0.9375 - val_loss: 0.1548
Epoch 22/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9397 - loss: 0.1333 - val_accuracy: 0.9438 - val_loss: 0.1354
Epoch 23/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9470 - loss: 0.1298 - val_accuracy: 0.9354 - val_loss: 0.1654
Epoch 24/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9355 - loss: 0.1309 - val_accuracy: 0.9375 - val_loss: 0.1648
Epoch 25/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9388 - loss: 0.1103 - val_accuracy: 0.9312 - val_loss: 0.1985
Epoch 26/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9299 - loss: 0.1148 - val_accuracy: 0.9333 - val_loss: 0.1812
Epoch 27/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9356 - loss: 0.1117 - val_accuracy: 0.9333 - val_loss: 0.1775
Epoch 28/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9312 - loss: 0.1222 - val_accuracy: 0.9333 - val_loss: 0.1858
Epoch 29/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9343 - loss: 0.1127 - val_accuracy: 0.9354 - val_loss: 0.1781
Epoch 30/30
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9363 - loss: 0.1134 - val_accuracy: 0.9375 - val_loss: 0.1792

In [ ]:
probs = model.predict(X_test).flatten()
print("Min:", probs.min())
print("Max:", probs.max())
print("Mean:", probs.mean())

19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Min: 7.649911e-24
Max: 0.9916868
Mean: 0.08866994

In [ ]:
manual_test(12, 10, 1.2, 0.45, 0, 0.2, 1, 0)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step

(np.float32(3.478898e-15), 'NORMAL USAGE ✅')

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(42)

data = []
TARGET_ROWS = 10000

while len(data) < TARGET_ROWS:
    behavior = np.random.choice(
        ["normal", "borderline", "atrisk", "doom"],
        p=[0.45, 0.25, 0.15, 0.15]
    )

    if behavior == "normal":
        duration = np.random.randint(5, 25)
        scrolls = np.random.randint(5, 25)
        app_switch = np.random.uniform(0.5, 2.0)
        idle_gap = np.random.uniform(0.35, 0.6)
        night = 0
        entertainment = np.random.uniform(0.1, 0.3)
        reopen = np.random.randint(0, 2)
        burst = 0
        label = 0

    elif behavior == "borderline":
        duration = np.random.randint(25, 40)
        scrolls = np.random.randint(20, 35)
        app_switch = np.random.uniform(2.0, 3.5)
        idle_gap = np.random.uniform(0.25, 0.35)
        night = np.random.choice([0, 1], p=[0.8, 0.2])
        entertainment = np.random.uniform(0.3, 0.5)
        reopen = np.random.randint(2, 4)
        burst = 0
        label = 0

    elif behavior == "atrisk":
        duration = np.random.randint(30, 50)
        scrolls = np.random.randint(30, 45)
        app_switch = np.random.uniform(3.0, 5.0)
        idle_gap = np.random.uniform(0.18, 0.28)
        night = np.random.choice([0, 1])
        entertainment = np.random.uniform(0.45, 0.65)
        reopen = np.random.randint(3, 6)
        burst = np.random.choice([0, 1], p=[0.7, 0.3])
        label = 1 if (night == 1 and entertainment > 0.6 and burst == 1) else 0

    else:  # doomscrolling
        duration = np.random.randint(50, 120)
        scrolls = np.random.randint(50, 90)
        app_switch = np.random.uniform(5.0, 9.0)
        idle_gap = np.random.uniform(0.02, 0.12)
        night = 1
        entertainment = np.random.uniform(0.7, 1.0)
        reopen = np.random.randint(7, 15)
        burst = 1
        label = 1

    data.append([
        duration,
        scrolls,
        round(app_switch, 2),
        round(idle_gap, 2),
        night,
        round(entertainment, 2),
        reopen,
        burst,
        label
    ])

df = pd.DataFrame(data, columns=[
    "session_duration_minutes",
    "scrolls_per_minute",
    "app_switch_rate",
    "idle_gap_ratio",
    "night_usage",
    "entertainment_ratio",
    "reopen_count",
    "session_burst_score",
    "doomscrolling"
])
print("Dataset shape:", df.shape)
print(df["doomscrolling"].value_counts())

# file_path = "/mnt/data/neuropulse_training_dataset_10k.csv"
# df.to_csv(file_path, index=False)

# file_path

Dataset shape: (10000, 9)
doomscrolling
0    8441
1    1559
Name: count, dtype: int64

In [ ]:
manual_test(35, 30, 2.5, 0.30, 0, 0.45, 3, 0)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

(np.float32(7.978571e-30), 'NORMAL USAGE ✅')

In [ ]:
df.to_csv("neuropulse_training_dataset.csv", index=False)

In [ ]:
from google.colab import files
files.download("neuropulse_training_dataset.csv")

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y  # VERY IMPORTANT
)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(24, activation="relu", input_shape=(8,)),
    Dense(12, activation="relu"),
    Dense(1, activation="sigmoid")
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 24)             │           216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 12)             │           300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            13 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 529 (2.07 KB)

 Trainable params: 529 (2.07 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from sklearn.utils.class_weight import compute_class_weight

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train),
    y=y_train
)

class_weight_dict = {
    0: class_weights[0],
    1: class_weights[1]
}

print("Class weights:", class_weight_dict)

NameError: name 'np' is not defined

In [ ]:
history = model.fit(
    X_train,
    y_train,
    epochs=30,              # sweet spot
    batch_size=32,
    validation_split=0.2,
    class_weight=class_weight_dict,
    verbose=1
)

NameError: name 'model' is not defined

In [ ]:
probs = model.predict(X_test).flatten()

print("Min:", probs.min())
print("Max:", probs.max())
print("Mean:", probs.mean())

19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
Min: 5.2791457e-13
Max: 0.74316037
Mean: 0.17566575

In [ ]:
manual_test(12, 10, 1.2, 0.45, 0, 0.2, 1, 0)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step

(np.float32(0.1362164), 'NORMAL USAGE ✅')

In [ ]:
manual_test(36, 32, 2.5, 0.30, 0, 0.45, 3, 0)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

(np.float32(0.22959547), 'NORMAL USAGE ✅')

In [ ]:
manual_test(70, 65, 6.0, 0.05, 1, 0.9, 10, 1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

(np.float32(0.73002684), 'MODERATE RISK ⚠️')

In [ ]:
import tensorflow as tf

model = tf.keras.models.load_model("neuropulse_mlp.keras")
print("✅ Model loaded")

ValueError: File not found: filepath=neuropulse_mlp.keras. Please ensure the file is an accessible `.keras` zip file.